### PR TITLE
Remove python 2 references

### PR DESCRIPTION
**Pull request by chrisinabox**
Update setup to include wxPython packages and remove  support for python 2
Update README to remove python 2 references

Cherry picked changes from b971ac0

### CODE REVIEW

**Comment by chrisinabox** [comment]
Ended up deleting the previous branch and cherry picking changes into a new branch as it became a little messy.

**Comment by sveinse** [comment]
Should we also use this branch to clean the code for py2 stuff and make this a true py3 package? Today there are quite many constructs for maintaining py2 compatibility. Without py2, we can now start type annotating the code (and in the process discover loads of bugs).

**Comment by sveinse** [comment]
> As I have no idea how much work that might require it may be worth distributing the updated py3 version (with this change) and then having a more significant clean up and refactor effort?

The PR #2 makes it incompatible with py2 doesn't it? If it does, I agree with you. Let's just commit this simple fix to remove it as something that's installable with py2 and leave the big py2 removal refactor for later.

**Comment by chrisinabox** [comment]
> > As I have no idea how much work that might require it may be worth distributing the updated py3 version (with this change) and then having a more significant clean up and refactor effort?
> 
> The PR #2 makes it incompatible with py2 doesn't it? If it does, I agree with you. Let's just commit this simple fix to remove it as something that's installable with py2 and leave the big py2 removal refactor for later.

I just did a preliminary test in a python 2 venv (windows). It seems that wxPython doesn't build properly with pip after 4.1.0. If using wxPython version 4.1.0 then it does at least appear to work (UI works, can open dictionaries without lots of errors).

**Pull request merged**
